pipeline {
    agent any

    tools {
        jdk 'jdk'
       
    }


    stages {
        stage('git checkout') {
            steps {
             checkout scmGit(branches: [[name: '*/main']],
             extensions: [sparseCheckout([[path: 'frontend']])],   // extensions: [[$class: 'SparseCheckoutPaths', sparseCheckoutPaths: [[path:'frontend']]]],
             userRemoteConfigs: [[url: 'https://github.com/kvnikhildev/Ecommerce-sample1.git']])  
            }
        }

        stage('git install package and lint check ') {
            steps {
                dir('frontend'){
                sh '''
                npm install
                npm run lint || true
                '''
                }
             
            }
        }

         stage('snyk test ') {
            steps {
                dir('frontend'){
                sh '''
                snyk $SNYK_TOKEN
                snyk test || true
                snyk monitor || true 
                '''
                }
             
            }
        }

        stage('sonarqube analysis') {
            steps {
                dir('frontend'){
                withSonarQubeEnv('SonarQube_Server') {
                    sh '''
                            npx sonar-scanner \
                            -Dsonar.projectKey=ecommerce-frontend \
                            -Dsonar.sources=. \
                        '''           
                    }
                }
            }

        }

        stage(' build the app') {
            steps {
                dir('frontend'){
                sh npm run build

                }
             
            }
        }

        stage(' create artifacts ') {
            steps {
                dir('frontend'){
                sh 'tar -czf ecommerce-frontend-artifact.tar.gz artifact/'
                
                }
             
            }
        }






    }
}


