apiVersion: v1
kind: Service
metadata:
  name: frontendapp
  labels:
    app: {{ .Values.labels.app }}
spec:
  type: NodePort
  selector:
      app: {{ .Values.labels.app }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodeport: 32146
 
