apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: {{ .Values.labels.app }}
spec:
  type: NodePort
  selector:
    labels:
      app: {{ .values.lables.app }}
  ports:
    - port: {{ .Values.port}}
      targetPort: {{ .Values.port}}
      nodeport: 32146
 
