            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: backend
              labels:
                app: {{ .Values.labels.app }}

            spec:
              replicas: {{ .Values.replicaCount }} 
              selector:
                matchLabels:
                  app: {{ .Values.labels.app }}
              template:
                metadata: 
                  name: backend
                  labels:
                    app: {{ .Values.labels.app }}
                spec:
                  containers:
                  - name: backend
                    image:  "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

