apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app:  {{ .Values.labels.app }}
spec:
  type: NodePort
  selector:
    labels:
      app: {{ .Values.labels.app }}

  
  ports:
    - port: 4000
      targetPort: 4000
      nodeport: 32145
  
