apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
      {{ .Release.Name }}
spec:
  selector:
    labels:
      {{ .Release.Name }}
  type: NodePort
  ports:
    - port: 4000
      targetPort: 4000
      nodeport: 32145
  
