apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
      {{ .Values.labels.app }}
spec:
  selector:
    labels:
      app: {{ .Values.labels.app }}
      
  type: NodePort
  ports:
    - port: 4000
      targetPort: 4000
      nodeport: 32145
  
