apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  selector:
      app: {{ .Values.labels.app }}

  
  ports:
    - port: 4000
      targetPort: 4000
      nodeport: 32145
  
